#!/bin/bash
rm ~/.Xresources
ln -s ~/.XresourcesAsuka ~/.Xresources
rm ~/.config/themer/current/startpage.html 
ln -s ~/.config/themer/current/startpageAsuka.html ~/.config/themer/current/startpage.html
rm ~/.config/themer/current/ff.css
ln -s ~/.config/themer/current/ff_asuka.css ~/.config/themer/current/ff.css
rm ~/.config/i3/config
ln -s ~/.config/i3/config_asuka ~/.config/i3/config
rm ~/.local/bin/rlb
ln -s ~/.local/bin/rlb_asuka ~/.local/bin/rlb
rm ~/.bashrc
ln -s ~/.bashrc_asuka ~/.bashrc
rm ~/.local/bin/bar.sh
ln -s ~/.local/bin/bar_asuka.sh ~/.local/bin/bar.sh
feh --bg-fill ~/pictures/backgrounds/asukablur_4k.png
source ~/.bashrc
pkill rlb
pkill bar.sh
nohup rlb &
reload-desktop
