#!/bin/bash
rm ~/.Xresources
ln -s ~/.XresourcesWheat ~/.Xresources
rm ~/.config/themer/current/startpage.html
ln -s ~/.config/themer/current/startpageDressing.html ~/.config/themer/current/startpage.html 
rm ~/.config/themer/current/ff.css
ln -s ~/.config/themer/current/ff_dressing.css ~/.config/themer/current/ff.css
rm ~/.config/i3/config
ln -s ~/.config/i3/config_cliff ~/.config/i3/config
rm ~/.local/bin/rlb
ln -s ~/.local/bin/rlb_dressing ~/.local/bin/rlb
feh --bg-fill ~/pictures/backgrounds/wheatgrass.jpg
pkill rlb 
pkill bar.sh 
nohup rlb &
reload-desktop
