#!/bin/bash
rm ~/.Xresources
ln -s ~/.XresourcesSbttg ~/.Xresources
rm ~/.config/themer/current/startpage.html
ln -s ~/.config/themer/current/startpageSbttg.html ~/.config/themer/current/startpage.html 
rm ~/.config/themer/current/ff.css
ln -s ~/.config/themer/current/ff_sbttg.css ~/.config/themer/current/ff.css
rm ~/.config/i3/config
ln -s ~/.config/i3/config_sbttg ~/.config/i3/config
rm ~/.local/bin/rlb
ln -s ~/.local/bin/rlb_sbttg ~/.local/bin/rlb
rm ~/.bashrc
ln -s ~/.bashrc_sbttg ~/.bashrc
rm ~/.local/bin/bar.sh
ln -s ~/.local/bin/bar_sbttg.sh ~/.local/bin/bar.sh
feh --bg-fill ~/pictures/backgrounds/sungrain.jpg
source ~/.bashrc 
pkill rlb 
pkill bar.sh 
nohup rlb &
reload-desktop
